# Generated by Django 4.0 on 2022-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybdbmodels',
            name='img',
            field=models.ImageField(default='no_image.jpg', upload_to='product.image'),
        ),
        migrations.AlterField(
            model_name='cybdbmodels',
            name='title',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
