# Generated by Django 4.0 on 2022-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cybdbmodels_img_alter_cybdbmodels_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybdbmodels',
            name='link',
            field=models.TextField(default='abc', verbose_name='link'),
        ),
    ]
